%{ for disk in data_disks }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvm-setup-${disk.name}
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: lvm
  template:
    metadata:
      labels:
        app: lvm
    spec:
      volumes:
      - name: hostfs
        hostPath:
          path: /
      containers:
      - image: alpine
        name: lvm-info
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          while sleep 60; do
            echo ----------------------------------------
            date
            chroot /hostfs/ pvdisplay -m ${disk.dev}
          done
      initContainers:
      - image: alpine
        name: lvm-setup
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          set -ex
            apk add --no-cache lvm2
            if ! chroot /hostfs lvdisplay ${disk.name}/pool &>/dev/null ; then
                echo "Creating ${disk.name}-pool on ${disk.dev}."
                pvcreate --yes -ff ${disk.dev}
                vgcreate --yes ${disk.name} ${disk.dev}
                lvcreate --yes -n MetadataLV -L 64M ${disk.name} ${disk.dev}:0-31
                lvcreate --yes -n pool -l 100%FREE ${disk.name} ${disk.dev}:32-
                lvconvert --yes --type thin-pool --poolmetadata MetadataLV ${disk.name}/pool
            fi
%{ endfor ~}
