name: Workflow for building and pushing vmware installer and ova image

on:
  workflow_dispatch:
  push:
    branches:
      - vmware
    paths:
      - '.github/workflows/image-build.yaml'
      - 'profile-image.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        talos_version: [v1.11.3]
        arch: [amd64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # To avoid disk space issues when performing a release, we can clear up some disk space ahead of time
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # we're likely already using some of the globally installed tools
          tool-cache: false
          docker-images: false
          # but we're definitely not using these
          android: true
          dotnet: true
          haskell: true
          # and shouldn't be using swap storage
          swap-storage: true
          # slow remove
          large-packages: false

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Installer
        env:
          ARCH: ${{ matrix.arch }}
          OUTPUT: installer
        run: |
          envsubst <profile-image.yaml | docker run --rm -i -v /dev:/dev --privileged \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${{ matrix.talos_version }}" -
          docker load -i ./_out/installer-${ARCH}.tar
          docker tag ghcr.io/siderolabs/installer:${{ matrix.talos_version }} ghcr.io/${{ github.repository }}/installer:vmware-${{ matrix.talos_version }}-${{ matrix.arch }}
          docker push ghcr.io/${{ github.repository }}/installer:vmware-${{ matrix.talos_version }}-${{ matrix.arch }}

      - name: Create ISO
        env:
          ARCH: ${{ matrix.arch }}
          OUTPUT: image
        run: |
          envsubst <profile-image.yaml | docker run --rm -i -v /dev:/dev --privileged \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${{ matrix.talos_version }}" -

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "vmware-${{ matrix.talos_version }}-${{ matrix.arch }}.ova"
          path: "_out/vmware-${{ matrix.arch }}.ova"
