name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -diff -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test (root)
        run: |
          terraform init
          terraform test

      - name: Terraform Test (modules/talos_k8s)
        run: |
          cd modules/talos_k8s
          terraform init
          terraform test

      - name: Terraform Test (modules/vms_proxmox)
        run: |
          cd modules/vms_proxmox
          terraform init
          terraform test
